update kubevirt libvirt-src template

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-src.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-src.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-src.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-src.yaml
@@ -88,112 +88,89 @@ objects:
       - /usr/bin/openshift-tests
       - /tmp/shared/openshift-tests
 
+    - name: kubevirt-src
+      image: ${LOCAL_IMAGE_SRC}
+      volumeMounts:
+      - name: shared-tmp
+        mountPath: /tmp/shared
+      command:
+      - cp
+      - -R
+      - /go/src/kubevirt.io/kubevirt
+      - /tmp/shared/kubevirt
+
     containers:
 
     # Once the cluster is up, executes shared tests
     - name: test
-      image: ${LOCAL_IMAGE_SRC}
+      image: ${IMAGE_LIBVIRT_INSTALLER}
       terminationMessagePolicy: FallbackToLogsOnError
       volumeMounts:
-        - name: shared-tmp
-          mountPath: /tmp/shared
-        - name: cluster-profile
-          mountPath: /tmp/cluster
-        - name: artifacts
-          mountPath: /tmp/artifacts
+      - name: shared-tmp
+        mountPath: /home/packer
+      - name: cluster-profile
+        mountPath: /tmp/cluster
+      - name: artifacts
+        mountPath: /tmp/artifacts
       env:
-        - name: AWS_SHARED_CREDENTIALS_FILE
-          value: /tmp/cluster/.awscred
-        - name: AZURE_AUTH_LOCATION
-          value: /tmp/cluster/osServicePrincipal.json
-        - name: GCP_SHARED_CREDENTIALS_FILE
-          value: /tmp/cluster/gce.json
-        - name: ARTIFACT_DIR
-          value: /tmp/artifacts
-        - name: HOME
-          value: /tmp/home
-        - name: IMAGE_FORMAT
-          value: ${IMAGE_FORMAT}
-        - name: KUBECONFIG
-          value: /tmp/artifacts/installer/auth/kubeconfig
+      - name: HOME
+        value: /home/packer
+      - name: NSS_WRAPPER_PASSWD
+        value: /home/packer/passwd
+      - name: NSS_WRAPPER_GROUP
+        value: /home/packer/group
+      - name: NSS_USERNAME
+        value: packer
+      - name: NSS_GROUPNAME
+        value: packer
+      - name: GOOGLE_PROJECT_ID
+        value: openshift-gce-devel-ci
+      - name: GOOGLE_COMPUTE_ZONE
+        value: us-east1-c
+      - name: INSTANCE_PREFIX
+        value: ${NAMESPACE}-${JOB_NAME_HASH}
+      - name: GCP_SHARED_CREDENTIALS_FILE
+        value: /tmp/cluster/gce.json
+      - name: ARTIFACT_DIR
+        value: /tmp/artifacts
       command:
-        - /bin/bash
-        - -c
-        - |
-          #!/bin/bash
-          set -euo pipefail
+      - /bin/bash
+      - -c
+      - |
+        #!/bin/sh
+        set -euo pipefail
+        trap 'touch "${HOME}"/exit' EXIT
+        trap 'kill $(jobs -p); exit 0' TERM
+        set -x
+        export GOOGLE_APPLICATION_CREDENTIALS="${GCP_SHARED_CREDENTIALS_FILE}"
+        [ -d "${HOME}"/.ssh ] || mkdir -p ~/.ssh
 
-          export PATH=/tmp/shared:$PATH
+        mock-nss.sh
+        gcloud auth activate-service-account --key-file="${GCP_SHARED_CREDENTIALS_FILE}"
+        gcloud --quiet config set project openshift-gce-devel-ci
+        gcloud --quiet config set compute/zone "${GOOGLE_COMPUTE_ZONE}"
+        set +x
 
-          trap 'touch /tmp/shared/exit' EXIT
-          trap 'kill $(jobs -p); exit 0' TERM
-
-          mkdir -p "${HOME}"
-
-          # wait for the API to come up
-          while true; do
-            if [[ -f /tmp/shared/exit ]]; then
-              echo "Another process exited" 2>&1
-              exit 1
-            fi
-            if [[ ! -f /tmp/shared/setup-success ]]; then
-              sleep 15 & wait
-              continue
-            fi
-            # don't let clients impact the global kubeconfig
-            cp "${KUBECONFIG}" /tmp/admin.kubeconfig
-            export KUBECONFIG=/tmp/admin.kubeconfig
-            break
-          done
-
-          # if the cluster profile included an insights secret, install it to the cluster to
-          # report support data from the support-operator
-          if [[ -f /tmp/cluster/insights-live.yaml ]]; then
-            oc create -f /tmp/cluster/insights-live.yaml || true
+        SETUP_SUCCESS=
+        while true; do
+          if [[ -f "${HOME}"/exit ]]; then
+            echo "Another process exited" 2>&1
+            exit 1
           fi
-
-          function setup-google-cloud-sdk() {
-            pushd /tmp
-            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-256.0.0-linux-x86_64.tar.gz
-            tar -xzf google-cloud-sdk-256.0.0-linux-x86_64.tar.gz
-            export PATH=$PATH:/tmp/google-cloud-sdk/bin
-            mkdir gcloudconfig
-            export CLOUDSDK_CONFIG=/tmp/gcloudconfig
-            gcloud auth activate-service-account --key-file="${GCP_SHARED_CREDENTIALS_FILE}"
-            gcloud config set project openshift-gce-devel-ci
-            popd
-          }
-
-          # set up cloud-provider-specific env vars
-          export KUBE_SSH_BASTION="$( oc --insecure-skip-tls-verify get node -l node-role.kubernetes.io/master -o 'jsonpath={.items[0].status.addresses[?(@.type=="ExternalIP")].address}' ):22"
-          export KUBE_SSH_KEY_PATH=/tmp/cluster/ssh-privatekey
-          if [[ "${CLUSTER_TYPE}" == "gcp" ]]; then
-            export GOOGLE_APPLICATION_CREDENTIALS="${GCP_SHARED_CREDENTIALS_FILE}"
-            export KUBE_SSH_USER=core
-            mkdir -p ~/.ssh
-            cp /tmp/cluster/ssh-privatekey ~/.ssh/google_compute_engine || true
-            export TEST_PROVIDER='{"type":"gce","region":"us-east1","multizone": true,"multimaster":true,"projectid":"openshift-gce-devel-ci"}'
-          elif [[ "${CLUSTER_TYPE}" == "aws" ]]; then
-            mkdir -p ~/.ssh
-            cp /tmp/cluster/ssh-privatekey ~/.ssh/kube_aws_rsa || true
-            export PROVIDER_ARGS="-provider=aws -gce-zone=us-east-1"
-            # TODO: make openshift-tests auto-discover this from cluster config
-            REGION="$(oc get -o jsonpath='{.status.platformStatus.aws.region}' infrastructure cluster)"
-            ZONE="$(oc get -o jsonpath='{.items[0].metadata.labels.failure-domain\.beta\.kubernetes\.io/zone}' nodes)"
-            export TEST_PROVIDER="{\"type\":\"aws\",\"region\":\"${REGION}\",\"zone\":\"${ZONE}\",\"multizone\":true,\"multimaster\":true}"
-            export KUBE_SSH_USER=core
-          elif [[ "${CLUSTER_TYPE}" == "azure4" ]]; then
-            export TEST_PROVIDER='azure'
-          elif [[ "${CLUSTER_TYPE}" == "openstack" ]]; then
-            mkdir -p ~/.ssh
-            cp /tmp/cluster/ssh-privatekey ~/.ssh/kube_openstack_rsa || true
+          if [[ ! -f "${HOME}"/setup-success ]]; then
+            sleep 15 & wait
+            continue
+          elif [[ -z "${SETUP_SUCCESS}" ]]; then
+            echo "Setup success"
+            SETUP_SUCCESS=1
           fi
-
-          if [[ "${CLUSTER_TYPE}" == "gcp" ]]; then
-            setup-google-cloud-sdk
-          fi
-
-          ${TEST_COMMAND}
+          break
+        done
+        set -x
+        LD_PRELOAD=/usr/lib64/libnss_wrapper.so gcloud compute --project "${GOOGLE_PROJECT_ID}" ssh \
+          --zone "${GOOGLE_COMPUTE_ZONE}" \
+          packer@"${INSTANCE_PREFIX}" \
+          --command 'export KUBECONFIG=/home/packer/clusters/installer/auth/kubeconfig && /home/packer/run-tests.sh'
 
     # Runs an install
     - name: setup
@@ -230,6 +207,65 @@ objects:
         set -euo pipefail
         trap 'rc=$?; if test "${rc}" -eq 0; then touch "${HOME}"/setup-success; else touch "${HOME}"/exit; fi; exit "${rc}"' EXIT
         trap 'CHILDREN=$(jobs -p); if test -n "${CHILDREN}"; then kill ${CHILDREN} && wait; fi' TERM
+        cat  > "${HOME}"/kubevirt-tests.sh << 'EOF'
+        #!/bin/bash
+        set -euo pipefail
+        echo "installing docker"
+        sudo yum install -y docker
+        sudo systemctl start docker
+        echo "fetching oc and kubectl for deployment"
+        export oc_filename='oc.tar.gz'
+        export oc_dirname="${oc_filename%.tar.gz}"
+        export oc_download_url_base='https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.2/linux/'
+        (
+          mkdir ${oc_dirname}
+          cd ${oc_dirname}
+          curl -L -O -o ${oc_filename} ${oc_download_url_base}/${oc_filename}
+          tar zxvf ${oc_filename}
+          ln -s $(pwd)/${oc_dirname} kubectl
+        ) || ( echo "failed to download ${oc_filename}"; exit 1 )
+        export PATH=$(pwd)/${oc_dirname}:$PATH
+        export KUBECONFIG=/home/packer/clusters/installer/auth/kubeconfig
+        which kubectl
+        which oc
+        echo "checking nodes for cluster"
+        oc get nodes
+        echo "checking configuration"
+        env|grep KUBE
+        kubectl config view
+        export DOCKER_PREFIX='dhiller'
+        export DOCKER_TAG="latest"
+        export KUBEVIRT_PROVIDER=external
+        export GIMME_GO_VERSION=1.12.8
+        export GOPATH="/go"
+        export GOBIN="/usr/bin"
+        sudo mkdir -p /gimme
+        sudo chmod 777 /gimme
+        sudo chmod 777 /etc/profile.d
+        sudo curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | HOME=/gimme GIMME_GO_VERSION=1.12.8 bash >> /etc/profile.d/gimme.sh
+        source /etc/profile.d/gimme.sh
+        echo "creating manifests"
+        sudo bash -x ./hack/build-manifests.sh
+        echo "checking configuration location" 
+        echo "KUBECONFIG: ${KUBECONFIG}"
+        echo "patching cluster-up external provider"
+        (
+          cd cluster-up/cluster/external
+          curl -L -O -o provider.sh https://raw.githubusercontent.com/dhiller/kubevirtci/fix-external-provider/cluster-up/cluster/external/provider.sh
+        )
+        echo "calling cluster-up to prepare config and check whether cluster is reachable"
+        bash -x ./cluster-up/up.sh echo "checking cluster configuration after config prep"
+        kubectl config view
+        echo "deploying"
+        bash -x ./hack/cluster-deploy.sh
+        echo "checking pods for kubevirt"
+        oc get pods -n kubevirt
+        echo "testing"
+        go get -u github.com/onsi/ginkgo/ginkgo
+        bash -x ./hack/build-func-tests.sh
+        bash -x ./hack/functests.sh
+        EOF
+        chmod +x "${HOME}"/kubevirt-tests.sh
         cat  > "${HOME}"/run-tests.sh << 'EOF'
         #!/bin/bash
         set -euo pipefail
@@ -237,8 +273,8 @@ objects:
         mkdir -p /tmp/artifacts/junit
 
         function run-tests() {
-          openshift-tests run "${TEST_SUITE}" \
-            -o /tmp/artifacts/e2e.log --junit-dir /tmp/artifacts/junit
+          cd kubevirt
+          "${HOME}"/kubevirt/kubevirt-tests.sh 
           return 0
         }
 
@@ -246,7 +282,7 @@ objects:
         EOF
         chmod +x "${HOME}"/run-tests.sh
         mock-nss.sh
-        mkdir "${HOME}"/.ssh
+        [ -d "${HOME}"/.ssh ] || mkdir "${HOME}"/.ssh
         gcloud auth activate-service-account \
           --quiet --key-file /tmp/cluster/gce.json
         gcloud --quiet config set project "${GOOGLE_PROJECT_ID}"
@@ -263,6 +299,16 @@ objects:
           --boot-disk-type pd-ssd \
           --boot-disk-size 256GB \
           --metadata-from-file openshift-pull-secret=/tmp/cluster/pull-secret
+        LD_PRELOAD=/usr/lib64/libnss_wrapper.so gcloud compute scp \
+          --quiet \
+          --project "${GOOGLE_PROJECT_ID}" \
+          --zone "${GOOGLE_COMPUTE_ZONE}" \
+          --recurse /home/packer/kubevirt packer@"${INSTANCE_PREFIX}":~/
+        LD_PRELOAD=/usr/lib64/libnss_wrapper.so gcloud compute scp \
+          --quiet \
+          --project "${GOOGLE_PROJECT_ID}" \
+          --zone "${GOOGLE_COMPUTE_ZONE}" \
+          --recurse "${HOME}"/kubevirt-tests.sh packer@"${INSTANCE_PREFIX}":~/kubevirt/kubevirt-tests.sh
         LD_PRELOAD=/usr/lib64/libnss_wrapper.so gcloud compute scp \
           --quiet \
           --project "${GOOGLE_PROJECT_ID}" \
